import iiif_downloader

ver_dict = {
    "2": {
        'dir': 'manifests2',
        'txt': 'manifests2.txt',
        "ids" : [
            { "tot" : 40, "na": 0 },
            { "tot" : 671, "na": 0 },
            { "tot" : 120, "na": 0 },
            { "tot" : 302, "na": 0 },
            { "tot" : 432, "na": 0 },
            { "tot" : 145, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 16, "na": 0 },
            { "tot" : 565, "na": 0 },
            { "tot" : 196, "na": 0 },
            { "tot" : 100, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 788, "na": 0 },
            { "tot" : 667, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 181, "na": 0 },
            { "tot" : 3, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 84, "na": 0 },
            { "tot" : 29, "na": 0 },
            { "tot" : 34, "na": 0 },
            { "tot" : 112, "na": 0 },
            { "tot" : 340, "na": 0 },
            { "tot" : 99, "na": 0 },
            { "tot" : 322, "na": 84 },
            { "tot" : 1, "na": 0 },
            { "tot" : 3, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 3, "na": 0 },
            { "tot" : 937, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 26, "na": 0 },
            { "tot" : 28, "na": 0 },
            { "tot" : 60, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 510, "na": 0 },
            { "tot" : 210, "na": 0 },
            { "tot" : 41, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 4, "na": 0 },
            { "tot" : 26, "na": 0 },
            { "tot" : 61, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 74, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 44, "na": 0 },
            { "tot" : 8, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 186, "na": 0 },
            { "tot" : 4, "na": 0 },
            { "tot" : 18, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 13, "na": 0 },
            { "tot" : 53, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 104, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 13, "na": 0 },
            { "tot" : 226, "na": 0 },
            { "tot" : 101, "na": 0 },
            { "tot" : 158, "na": 0 },
            { "tot" : 37, "na": 0 },
            { "tot" : 20, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 162, "na": 0 },
         ]
    },

    "3": {
        'dir': 'manifests3',
        'txt': 'manifests3.txt',
        "ids" : [
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 5, "na": 0 },
            { "tot" : 4, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 5, "na": 0 },
            { "tot" : 4, "na": 1 },
            { "tot" : 1, "na": 0 },
            { "tot" : 5, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 59, "na": 0 },
            { "tot" : 43, "na": 0 },
            { "tot" : 305, "na": 0 },
            { "tot" : 1294, "na": 0 },
            { "tot" : 3, "na": 0 },
            { "tot" : 13, "na": 0 },
            { "tot" : 1, "na": 0 },
            { "tot" : 27, "na": 0 },
            { "tot" : 2, "na": 0 },
            { "tot" : 601, "na": 0 },
            { "tot" : 1, "na": 0 },
        ]
    }
}
