#!/bin/sh

# Initialize errors
errors=0

# Run flake8 on Python codes
echo "[Info] Running flake8"
flake8 iiif_downloader.py
exit_code=$?
((errors+=exit_code))
flake8 iiif_downloader_gui.py
exit_code=$?
((errors+=exit_code))

# Run mypy on Python codes
echo "[Info] Running mypy"
mypy iiif_downloader_gui.py --strict  # it checks iiif_downloader.py too
exit_code=$?
((errors+=exit_code))

# Run pylint on Python codes
# pylint returns bit-encoded exit codes where fatals=1, errors=2, warnings=4...
# We ignore convention and refactoring checks, hence the exit code is always < 7
# We ignore some warnings (too general exceptions). The exit code should be 0.
echo "[Info] Running pylint"
pylint iiif_downloader.py --enable=all --disable=C,R,W0718,W0719
exit_code=$?
((errors+=exit_code))
pylint iiif_downloader_gui.py --enable=all --disable=C,R,W0718,W0719
exit_code=$?
((errors+=exit_code))

# Go to testing directory
cd testing 

# Unzip manifest archives, if needed
if [ ! -f manifests2/manifest00.json ]; then
  echo "[Info] Unzipping manifests2 archive"
  unzip -q manifests2/archive2.zip -d manifests2
else
  echo "[Info] No need to unzip manifests2 archive"
fi
if [ ! -f manifests3/manifest00.json ]; then
  echo "[Info] Unzipping manifests3 archive"
  unzip -q manifests3/archive3.zip -d manifests3
else
  echo "[Info] No need to unzip manifests3 archive"
fi

# Run unit tests
echo "[Info] Running basic tests"
python3 test_all.py --metadata
exit_code=$?
((errors+=exit_code))
echo "[Info] Running GUI tests"
python3 test_gui_all.py
exit_code=$?
((errors+=exit_code))

# Delete unzipped files
echo "[Info] Deleting unzipped manifests"
rm manifests2/*.json
rm manifests3/*.json

# Final check (errors should be zero)
if [ $errors -ne 0 ]; then
  echo "[Verdict] Something is wrong. You can't commit."
  exit 1
else
  echo "[Verdict] Everything is good. You can commit."
  exit 0
fi
